# on: push
# jobs:
#   first-job:
#     runs-on: windows-latest
#     steps:
#       - run: node --version
#       - run: npm --version

name: MongoDB CRUD Operations

on:
  # You can customize this to run on specific triggers
  push:
    branches:
      - main
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  perform-crud-operations:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run CRUD operations
      run: |
        # Define your MongoDB connection URI, e.g., mongodb://username:password@host:port/dbname
        $mongo_uri = "mongodb://username:password@localhost:27017/mydb"
        
        # Example CRUD operations:
        # Replace the below MongoDB shell commands with your desired CRUD operations

        # Create a document in the 'users' collection
        echo 'db.users.insert({ name: "Alice", age: 30 })' | mongo $mongo_uri
        
        # Read documents from the 'users' collection
        echo 'db.users.find({})' | mongo $mongo_uri
        
        # Update a document in the 'users' collection
        echo 'db.users.updateOne({ name: "Alice" }, { $set: { age: 31 } })' | mongo $mongo_uri
        
        # Delete a document from the 'users' collection
        echo 'db.users.deleteOne({ name: "Alice" })' | mongo $mongo_uri
        
        # Add more commands as needed

    # Add more steps if necessary
